sudo: true
dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_USERNAME/teaweb:build_new

jobs:
  include:
    - stage: "build"
      name: TeaWeb build master branch
      script:
        - "mkdir -p /tmp/build"
        - "docker run --rm -v /tmp/build/logs/:/build/logs/ -v /tmp/build/packages/:/build/packages/ -v `pwd`:/build/TeaWeb $DOCKER_USERNAME/teaweb:build_new --enable-release --enable-debug || travis_terminate 1;"
        - "./scripts/travis_deploy.sh || travis_terminate 1;"
      if: branch = master