sudo: true
dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker pull $DOCKER_USERNAME/teaweb:build_new
  - docker images

jobs:
  include:
    - stage: "build"
      name: TeaWeb build master branch
      script:
        - "echo \"$SHIPPABLE_BUILD_DIR\""
        - "echo \"$SHIPPABLE_DATA_DIR\""
        - "docker run --rm -v $SHIPPABLE_DATA_DIR/build/logs/:/build/logs/ -v $SHIPPABLE_DATA_DIR/build/packages/:/build/packages/ -v $SHIPPABLE_BUILD_DIR:/build/TeaWeb $DOCKER_USERNAME/teaweb:build_new --enable-release --enable-debug"
        - "ls -lah $SHIPPABLE_DATA_DIR/build/"
        - "ls -lah $SHIPPABLE_DATA_DIR/build/logs/"
        - "ls -lah $SHIPPABLE_DATA_DIR/build/packages/"
      #TODO: Upload!
    - stage: "deploy"
      name: Deploy the builded files as official release
      script:
        - echo "Implement me!"
      if: branch = master