sudo: true
dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker pull $DOCKER_USERNAME/teaweb:build_new
  - docker images

jobs:
  include:
    - stage: "build"
      name: TeaWeb build master branch
      script:
        - "mkdir -p /tmp/build"
        - "docker run --rm -v /tmp/build/logs/:/build/logs/ -v /tmp/build/packages/:/build/packages/ -v `pwd`:/build/TeaWeb $DOCKER_USERNAME/teaweb:build_new --enable-release --enable-debug"
        - "ls -lah /tmp/build/"
        - "ls -lah /tmp/build/logs/"
        - "ls -lah /tmp/build/packages/"
        - >
          mkdir -p /tmp/build/packages/;
          echo "XXXX" > /tmp/build/packages/xxxxx;
          ./scripts/travis_deploy.sh
      if: branch = master