sudo: true
dist: trusty

cache:
  bundler: true
  directories:
  - $HOME/docker

before_cache:
# Save tagged docker images
- >
  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
# Load cached docker images
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

jobs:
  include:
    - stage: build teaweb
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
      - docker pull $DOCKER_USERNAME/teaweb:build
      - docker images
      - docker run --rm $DOCKER_USERNAME/teaweb /bin/bash -c /root/build_teaweb.sh travis
      if: branch = master
    - stage: test teaweb build
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
      - docker pull $DOCKER_USERNAME/teaweb:build
      - docker images
      - docker run --rm teaweb:build /bin/bash -c /root/build_teaweb.sh
      if: branch != master