dist: trusty

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  # If ever run on windows make sure you don't run this in the git bash!
  - docker run -dit --name emscripten -v "$(pwd)":"/src/" trzeci/emscripten:sdk-incoming-64bit bash
  - chmod +x ./scripts/travis.sh
  - chmod +x ./scripts/travis_deploy_dev_server.sh
  - chmod +x ./scripts/travis_deploy_github.sh

stages:
  - compile
  # - test We've no tested defined yet

jobs:
  include:
    - stage: compile
      script: "./scripts/travis.sh --enable-release --enable-debug || travis_terminate 1;"

deploy:
  - provider: script
    script: "./scripts/travis_deploy_dev_server.sh || travis_terminate 1;"
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: "./scripts/travis_deploy_github.sh || travis_terminate 1;"
    on:
      branch: master