sudo: true
dist: trusty

jobs:
  include:
    - stage: build teaweb
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
      - docker pull $DOCKER_USERNAME/teaweb:build
      - docker images
      - docker run --rm teaweb:build /bin/bash -c /root/build_teaweb.sh travis
      if: branch = master
    - stage: test teaweb
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
      - docker pull $DOCKER_USERNAME/teaweb:build
      - docker images
      - docker run --rm teaweb:build /bin/bash -c /root/build_teaweb.sh
      if: branch != master