dist: trusty

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  # If ever run on windows make sure you don't run this in the git bash!
  - docker run -dit --name emscripten -v "$(pwd)":"/src/" trzeci/emscripten:sdk-incoming-64bit bash
  - chmod +x ./scripts/travis.sh
  - chmod +x ./scripts/travis_deploy_dev_server.sh
  - chmod +x ./scripts/travis_deploy_github.sh

stages:
  - compile
  # - test We've no tested defined yet

jobs:
  include:
    - stage: compile
      script: "./scripts/travis.sh --enable-release --enable-debug || travis_terminate 1;"

deploy:
  - provider: script
    script: "bash  scripts/travis_deploy_dev_server.sh"
    cleanup: false
    on:
      branch: develop
  - provider: script
    cleanup: false
    script: "bash  scripts/travis_deploy_github.sh"
    on:
      branch: master