sudo: true
dist: trusty

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker pull $DOCKER_USERNAME/teaweb:build_new
  - docker images

jobs:
  include:
    - stage: "build"
      name: TeaWeb build master branch
      script:
        - "mkdir -p /tmp/build"
        - "docker run --rm -v /tmp/build/logs/:/build/logs/ -v /tmp/build/packages/:/build/packages/ -v `pwd`:/build/TeaWeb $DOCKER_USERNAME/teaweb:build_new --enable-release --enable-debug"
        - "ls -lah /tmp/build/"
        - "ls -lah /tmp/build/logs/"
        - "ls -lah /tmp/build/packages/"
        - "wget https://github.com/buildkite/github-release/releases/download/v1.0/github-release-linux-amd64 -O /tmp/git-release; chmod +x /tmp/git-release;"
        - "echo \"Release commit: $COMMIT\"; export GITHUB_RELEASE_COMMIT=\"$COMMIT\""
        - "export GITHUB_RELEASE_TAG=\"This is a auto build release from travis\""
        - "export GITHUB_RELEASE_REPOSITORY=\"$REPO_FULL_NAME\""
        - "export GITHUB_RELEASE_ACCESS_TOKEN=\"$GIT_AUTHTOKEN\""
        - "/tmp/git-release \"Travis autobuild $COMMIT\" /tmp/build/packages/* /tmp/build/logs/*"
      if: branch = master