sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
      - docker pull $DOCKER_USERNAME/teaweb
      - docker images
    - stage: build
      script:
      - docker run --rm teaweb:build /bin/bash -c "ls -lah"