sudo: true
dist: trusty

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  # If ever run on windows make sure you don't run this in the git bash!
  - docker run -dit --name emscripten -v "$(pwd)":"/src/" trzeci/emscripten:sdk-incoming-64bit bash

jobs:
  include:
    - stage: "build"
      name: TeaWeb build master branch
      script:
        - "./scripts/travis.sh --enable-release --enable-debug || travis_terminate 1;"
        - "./scripts/travis_deploy.sh || travis_terminate 1;"
      if: branch = master