sudo: required
dist: trusty

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  # If ever run on windows make sure you don't run this in the git bash!
  - docker run -dit --name emscripten -v "$(pwd)":"/src/" trzeci/emscripten:sdk-incoming-64bit bash
  - chmod +x ./scripts/travis.sh
  - chmod +x ./scripts/travis_deploy.sh

script:
  - "./scripts/travis.sh --enable-release --enable-debug || travis_terminate 1;"
  - "./scripts/travis_deploy.sh || travis_terminate 1;"